
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUALIGUAL = 18;
  public static final int MENOR = 14;
  public static final int ELSE = 4;
  public static final int IGUAL = 9;
  public static final int INT = 3;
  public static final int WHILE = 7;
  public static final int SUMA = 10;
  public static final int MAYIGUAL = 17;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int ID = 29;
  public static final int NUM = 28;
  public static final int DO = 8;
  public static final int BRACKETRIGHT = 25;
  public static final int COMA = 21;
  public static final int MENIGUAL = 15;
  public static final int DISTINTO = 19;
  public static final int MAYOR = 16;
  public static final int EOF = 0;
  public static final int MULT = 11;
  public static final int DIV = 13;
  public static final int BRACKETLEFT = 24;
  public static final int PARENTHRIGHT = 23;
  public static final int PARENTHLEFT = 22;
  public static final int error = 1;
  public static final int BRACERRIGHT = 27;
  public static final int PUNTOCOMA = 20;
  public static final int VOID = 6;
  public static final int BRACERLEFT = 26;
  public static final int RESTA = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "INT",
  "ELSE",
  "RETURN",
  "VOID",
  "WHILE",
  "DO",
  "IGUAL",
  "SUMA",
  "MULT",
  "RESTA",
  "DIV",
  "MENOR",
  "MENIGUAL",
  "MAYOR",
  "MAYIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "PUNTOCOMA",
  "COMA",
  "PARENTHLEFT",
  "PARENTHRIGHT",
  "BRACKETLEFT",
  "BRACKETRIGHT",
  "BRACERLEFT",
  "BRACERRIGHT",
  "NUM",
  "ID"
  };
}

